identifier: l1p3gfj0dfu6tdc5
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: alpha-konstruksi-nusantara-web
homeFolder: E:\source\repos\Alpha Konstruksi Nusantara\Alpha Konstruksi Nusantara Web
distFolder: ./dist/alpha-konstruksi-nusantara-web/id
outDir: >-
  E:\source\repos\Alpha Konstruksi Nusantara\Alpha Konstruksi Nusantara
  Web\dist\static\
handle404: ''
allowErrorCollect: true
outHostFolder: ./dist/static/
hostFolder: ./dist/static/
